package com.misiunas.klab.gui.show;

import com.alee.laf.button.WebToggleButton;
import com.alee.laf.slider.WebSlider;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;

/**
 * User: karolis@misiunas.com
 * Date: 22/07/2013
 * Time: 02:08
 */
public class ShowParticleTrackFrame {

    private ShowParticleTrack spt;

    private JPanel panel1;
    private WebToggleButton playWebToggleButton;
    private WebSlider webSlider1;
    private JPanel processingPanel;
    private JLabel labelFrameIndicator;

    public void show(ShowParticleTrack s) {
        this.spt = s;
        System.out.println("point2: " + s);

        JFrame frame = new JFrame("ShowParticleTrackFrame");
        frame.setContentPane(this.panel1);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        processingPanel.add(spt);
        spt.init();
        frame.setVisible(true);
        processingPanel.revalidate();
        processingPanel.repaint();
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        processingPanel = new JPanel();
        System.out.println("point3: " + spt);
        //processingPanel.add(spt);
        //spt.init();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:600px:grow", "center:500px:grow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        CellConstraints cc = new CellConstraints();
        panel1.add(processingPanel, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:m:grow,left:5dlu:noGrow,center:max(p;100px):grow(10.0),left:4dlu:noGrow,fill:max(m;4px):noGrow", "center:d:grow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        panel1.add(panel2, cc.xy(1, 3));
        playWebToggleButton = new WebToggleButton();
        playWebToggleButton.setIcon(new ImageIcon(getClass().getResource("/com/misiunas/klab/gui/show/iMac.png")));
        playWebToggleButton.setText("Play");
        panel2.add(playWebToggleButton, cc.xy(1, 3, CellConstraints.LEFT, CellConstraints.DEFAULT));
        webSlider1 = new WebSlider();
        panel2.add(webSlider1, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.CENTER));
        labelFrameIndicator = new JLabel();
        labelFrameIndicator.setText("001 / 100");
        panel2.add(labelFrameIndicator, cc.xy(5, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
